document.getElementById("checkStatus").addEventListener("click", function() {
    const healthTips = [
        "Drink plenty of water every day.",
        "Take a walk for at least 30 minutes.",
        "Eat more fruits and vegetables.",
        "Get enough sleep—7-8 hours a night.",
        "Practice mindfulness or meditation daily.",
        "Stretch your body every morning for better flexibility.",
        "Avoid processed foods and eat natural foods.",
        "Incorporate physical activity into your daily routine.",
        "Limit your intake of sugary drinks and snacks.",
        "Take regular breaks from sitting—stand up and move around.",
        "Practice good hygiene, including regular hand washing.",
        "Use sunscreen to protect your skin from harmful UV rays.",
        "Get regular health check-ups and screenings.",
        "Maintain a balanced diet with a variety of nutrients.",
        "Reduce stress through relaxation techniques like deep breathing.",
        "Avoid smoking and excessive alcohol consumption.",
        "Get vaccinated to prevent infectious diseases.",
        "Eat whole grains instead of refined grains.",
        "Try to include protein in every meal for sustained energy.",
        "Limit your caffeine intake.",
        "Keep a food diary to monitor your eating habits.",
        "Cook more meals at home instead of eating out.",
        "Practice portion control to avoid overeating.",
        "Stay socially connected with friends and family.",
        "Engage in hobbies that you enjoy and find relaxing.",
        "Use ergonomic furniture to improve posture while working.",
        "Incorporate strength training exercises into your fitness routine.",
        "Take time each day for self-care and relaxation.",
        "Avoid skipping meals; eat regular, balanced meals.",
        "Opt for healthy snacks like nuts or yogurt.",
        "Drink herbal teas like chamomile for relaxation.",
        "Spend time in nature to boost mental well-being.",
        "Learn to manage time effectively to reduce stress.",
        "Make sure to get adequate calcium for bone health.",
        "Practice good dental hygiene by brushing and flossing regularly.",
        "Get regular physical exams and follow your doctor’s advice.",
        "Avoid excessive screen time—take regular breaks from screens.",
        "Eat foods rich in antioxidants to support overall health.",
        "Practice mindful eating—eat slowly and savor each bite.",
        "Engage in activities that challenge your brain, like puzzles.",
        "Keep hydrated by drinking water before, during, and after exercise.",
        "Try to reduce your intake of saturated and trans fats.",
        "Incorporate more omega-3 fatty acids into your diet.",
        "Ensure you have a comfortable sleeping environment.",
        "Set realistic health and fitness goals for yourself.",
        "Join a local fitness group or class for motivation.",
        "Limit your intake of high-sodium foods.",
        "Avoid eating heavy meals late at night.",
        "Practice positive thinking and affirmations for mental health.",
        "Invest in a quality mattress and pillows for better sleep.",
        "Avoid excessive consumption of red and processed meats.",
        "Ensure you get enough vitamin D through sunlight or supplements.",
        "Include fermented foods in your diet for gut health.",
        "Get involved in community activities to boost social well-being.",
        "Set aside time for hobbies that bring you joy.",
        "Incorporate more fiber into your diet for digestive health.",
        "Avoid multitasking during meals—focus on eating.",
        "Limit your intake of sugary cereals and snacks.",
        "Learn relaxation techniques to manage anxiety and stress.",
        "Take regular walks or bike rides to increase physical activity.",
        "Maintain a healthy weight through balanced diet and exercise.",
        "Avoid excessive intake of energy drinks and sodas.",
        "Use a fitness tracker to monitor your physical activity.",
        "Include healthy fats, like avocados, in your diet.",
        "Learn about nutrition and how different foods affect health.",
        "Practice gratitude and positive thinking to boost mental health.",
        "Eat a variety of colored fruits and vegetables for a range of nutrients.",
        "Stay informed about health and wellness trends and research.",
        "Make time for regular relaxation and meditation sessions.",
        "Take care of your mental health by seeking support if needed.",
        "Use low-fat or non-fat dairy products when possible.",
        "Avoid eating large portions of fried or greasy foods.",
        "Find a workout buddy to stay motivated and accountable.",
        "Try different types of exercise to keep things interesting.",
        "Use a water bottle to stay hydrated throughout the day.",
        "Incorporate regular cardio workouts for heart health.",
        "Avoid excessive consumption of refined sugars and carbohydrates.",
        "Make sure to get enough magnesium for overall health.",
        "Try to incorporate yoga or stretching into your daily routine.",
        "Choose whole foods over processed snacks and meals.",
        "Regularly check your blood pressure and cholesterol levels.",
        "Practice good posture to prevent back and neck pain.",
        "Find healthy ways to manage and cope with stress.",
        "Include more plant-based meals in your diet.",
        "Avoid eating while watching TV or using your phone.",
        "Set aside time each day for physical activity.",
        "Make sure to have a balanced intake of vitamins and minerals.",
        "Use healthy cooking methods, such as baking or grilling.",
        "Listen to your body and get rest when needed.",
        "Include nuts and seeds in your diet for healthy fats.",
        "Practice mindful breathing to improve focus and relaxation.",
        "Take short breaks throughout your day to refresh and re-energize.",
        "Keep your living space clean and organized for a healthier environment.",
        "Stay updated on health and wellness information and practices.",
        "Make healthy choices when dining out.",
        "Avoid excessive use of artificial sweeteners.",
        "Practice portion control to manage weight effectively.",
        "Ensure you are getting enough iron in your diet.",
        "Avoid excessive use of salt in cooking.",
        "Incorporate more fresh herbs and spices for flavor and health benefits."
      ];
      

    const randomTip = healthTips[Math.floor(Math.random() * healthTips.length)];
    document.getElementById("tip").innerText = randomTip;
});
